name: Update data.json from Firebase

on:
  schedule:
    - cron: '*/5 * * * *'  # প্রতি ৫ মিনিটে রান
  workflow_dispatch:        # ম্যানুয়ালি ট্রিগার

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install node-fetch@3

      - name: Fetch Firebase JSON and update data.json
        run: |
          node -e "
          import fetch from 'node-fetch';
          import fs from 'fs';
          const url = 'https://my-book-project-c5a17-default-rtdb.asia-southeast1.firebasedatabase.app/movies.json';
          fetch(url)
            .then(res => res.json())
            .then(data => fs.writeFileSync('data.json', JSON.stringify(data, null, 2)))
            .catch(err => { console.error(err); process.exit(1); });
          "

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Auto-update data.json from Firebase" || echo "No changes to commit"
          git push
